### ISSUE TITLE
vac error?

### ISSUE THREAD

**Issue by KenZo2k2** [namazso/nSkinz#143] opened 2019-04-08 11:31 UTC
plz fix fasttttt

**Comment by Aethstetic** [comment] 2019-04-08 17:43
not sure if you realized this project has been dead for a good while now

**Comment by M1XT3NZ** [comment] 2019-04-08 17:45
It's not "dead"

There is just no need to update it?
The VAC error is probably a "you" problem. 

could be fixed with (vmprotect, etc)

**Comment by Jeimy041** [comment] 2019-04-19 00:17
Simple solution, take your dll, take your injector (I recommend rando injector), get VMProtect, go ahead and VMProtect both dll and the injector and fixed no more VAC errors

**Comment by namazso** [comment] 2021-01-04 14:26
duplicate of #27 / out of scope

**Closed by namazso** 2021-01-04 14:26 UTC
