### ISSUE TITLE
Skin changer the skin just overlaped with another

### ISSUE THREAD

**Issue by kurobaryo** [namazso/nSkinz#15] opened 2017-08-23 14:54 UTC
when i try to change the skin from one to another, the previous one will still appears on the item, they overlaped with each other, any solutions?

**Comment by namazso** [comment] 2017-11-27 12:20
can't reproduce

**Comment by namazso** [comment] 2018-03-15 13:13
was fixed in https://github.com/namazso/nSkinz/commit/da75e717dc9feada03c83b31c50b4e5766903d97

**Closed by namazso** 2018-03-15 13:13 UTC
