### ISSUE TITLE
Knife icon doesn't change in killfeed

### ISSUE THREAD

**Issue by lvntmaster** [namazso/nSkinz#148] opened 2019-05-16 20:25 UTC
https://imgur.com/a/WlhSqBt

**Comment by namazso** [comment] 2019-05-16 21:21
This is a known bug, this broke because the code still tries to hook the Scaleform killfeed HUD element's killfeed notification callback, while the game uses Panorama since quite some time.

Fixing shouldn't be too hard, just need a new sig and function index / subclass vtable offset.
I might look at it sometime (when i have time), but feel free to send a pr if you decide to fix it on your own.

**Comment by namazso** [comment] 2019-05-16 21:22
didn't notice, but this is actually a duplicate of #127

**Closed by namazso** 2019-05-16 21:22 UTC
Labels: bug

**Comment by lvntmaster** [comment] 2019-05-17 17:33
Thanks the answer. Sorry for duplicate!
