### ISSUE TITLE
Weapon -> Only skins for that weapon

### ISSUE THREAD

**Issue by cojo1989** [namazso/nSkinz#167] opened 2019-09-30 01:09 UTC
Hello guys, can somebody tell me how can i make nSkinz to show only the skins for selected weapon? Ex: If i choose AWP to show me only the skins for AWP.

Thank you very much.

**Comment by rawn7702** [comment] 2019-10-06 04:42
> Hello guys, can somebody tell me how can i make nSkinz to show only the skins for selected weapon? Ex: If i choose AWP to show me only the skins for AWP.
> 
> Thank you very much.

Need this feature man. Seriously !!!

**Comment by cojo1989** [comment] 2019-10-06 07:09
It`s seems nobody wants to help ...

**Comment by namazso** [comment] 2019-10-06 12:55
The game doesn't store this information, and I won't hardcode such thing. Besides, any skin can be applied to any weapon, and some such combinations look really nice.
I think this is probably a duplicate of an older issue, but can't find it.

**Closed by namazso** 2019-10-06 12:55 UTC
Labels: wontfix

**Comment by cojo1989** [comment] 2019-10-06 13:02
@namazso i agree with you i was thinking is an easy way to do it... but if you wont it`s ok. Thank you anyway.

**Comment by rawn7702** [comment] 2019-10-06 17:47
@namazso thank you for your reply. makes sense. You've worked hard for us already making this hack. Thank you <3

**Comment by rawn7702** [comment] 2019-10-06 17:49
Apart from that how can we apply 4 stickers to one weapon? I can only apply 1 sticker. @namazso

**Comment by M1XT3NZ** [comment] 2019-10-06 17:51
![Screenshot_4](https://user-images.githubusercontent.com/29348454/66273268-b3aebd80-e872-11e9-9f30-2d85f2b729af.png)
sry but are you blind?

**Comment by rawn7702** [comment] 2019-10-09 20:31
> ![Screenshot_4](https://user-images.githubusercontent.com/29348454/66273268-b3aebd80-e872-11e9-9f30-2d85f2b729af.png)
> sry but are you blind?

Ohw... I never noticed. So sorry. You don't have to be so rude man.
It was a harmless question.
._.

**Comment by M1XT3NZ** [comment] 2019-10-09 21:44
It wasn’t rude but if someone can’t see such a simple thing that is
directly in front of them...
