### ISSUE TITLE
15 errors while compiling

### ISSUE THREAD

**Issue by Werngod** [namazso/nSkinz#87] opened 2018-08-04 15:37 UTC
1>------ Build started: Project: nSkinz, Configuration: Release Win32 ------
1>render.cpp
1>c:\users\wern\desktop\nskinz-master\src\render.cpp(232): error C2039: 'ChildWindowRounding': is not a member of 'ImGuiStyle'
1>c:\users\wern\desktop\nskinz-master\src\imgui.h(1029): note: see declaration of 'ImGuiStyle'
1>c:\users\wern\desktop\nskinz-master\src\render.cpp(257): error C2065: 'ImGuiCol_ComboBg': undeclared identifier
1>c:\users\wern\desktop\nskinz-master\src\render.cpp(273): error C2065: 'ImGuiCol_CloseButton': undeclared identifier
1>c:\users\wern\desktop\nskinz-master\src\render.cpp(274): error C2065: 'ImGuiCol_CloseButtonHovered': undeclared identifier
1>c:\users\wern\desktop\nskinz-master\src\render.cpp(275): error C2065: 'ImGuiCol_CloseButtonActive': undeclared identifier
1>c:\users\wern\desktop\nskinz-master\src\render.cpp(366): error C2660: 'ImGui_ImplDX9_Init': function does not take 2 arguments
1>c:\users\wern\desktop\nskinz-master\deps\imgui\imgui_impl_dx9.h(13): note: see declaration of 'ImGui_ImplDX9_Init'
1>c:\users\wern\desktop\nskinz-master\src\render.cpp(366): error C2789: 'result': an object of const-qualified type must be initialized
1>c:\users\wern\desktop\nskinz-master\src\render.cpp(366): note: see declaration of 'result'
1>c:\users\wern\desktop\nskinz-master\src\render.cpp(368): error C3536: 'result': cannot be used before it is initialized
1>Done building project "nSkinz.vcxproj" -- FAILED.

help pls :/

**Comment by adilthequickdropper** [comment] 2018-08-04 16:05
try to retarget it

**Comment by Werngod** [comment] 2018-08-04 17:38
I thought it would work, but still same errors

**Comment by Jeimy041** [comment] 2018-08-04 20:27
Use the imgui version 1.52
That worked for me

**Comment by wine** [comment] 2018-08-10 12:41
Did you clone the source using `git clone --recursive https://github.com/namazso/nSkinz.git` or did you download it as a zip from the git page?

**Comment by namazso** [comment] 2018-08-19 10:27
duplicate of #56, #59, #52, #23

**Closed by namazso** 2018-08-19 10:27 UTC
