### ISSUE TITLE
vac error

### ISSUE THREAD

**Issue by ph4nt0m23** [namazso/nSkinz#159] opened 2019-09-21 16:51 UTC
Hey guys pls help I cant play for like 2 rounds and it says cannot play on vac secured servers pls help me

**Comment by anarh1st47** [comment] 2019-09-21 22:36
use undetected injector

**Comment by ph4nt0m23** [comment] 2019-09-23 04:53
what undetected injector can u recommend one

**Comment by ph4nt0m23** [comment] 2019-09-23 05:03
and how to do it do u have a tutorial

**Comment by namazso** [comment] 2019-09-28 23:52
duplicate of #27

**Closed by namazso** 2019-09-28 23:52 UTC
