### ISSUE TITLE
Vac Auth

### ISSUE THREAD

**Issue by yujispin990** [namazso/nSkinz#98] opened 2018-08-22 05:15 UTC
no idea why keeps vac auth...used a manual map and load library injector..still the same

**Comment by MadeInAZE** [comment] 2018-08-23 09:04
It is also same as the skinchanger official russian page skin changer. New update has fixed it. It is so hard to use skin changers these days......

**Comment by namazso** [comment] 2018-08-24 11:27
Duplicate of #39

**Closed by namazso** 2018-08-24 11:27 UTC
